### ISSUE TITLE
Suggestion: Add .tga export support

### ISSUE THREAD

**Issue by internetakias** [xdanieldzd/GXTConvert#2]
The DR PC ports use tga instead of gxt and I'm trying to back port some stuff from DR2 Vita to DR1 PC, so yeah

**Comment by xdanieldzd** [comment]
TGA export is a low priority at best, as PNG already supports all the features needed to export GXTs without losing information (alpha channel, palettes, etc.), and I'd have to roll my own TGA writing code or rely on an external library, because .NET does not support that format out of the box. Extra work for little to no gain, in my opinion.

You could try using an image viewer/converter like ex. IrfanView to convert the exported PNGs to TGAs, which should work just fine, assuming DR1 PC doesn't have some specific requirements for its TGAs (which would be out of the scope of GXTConvert anyway).

**Comment by internetakias** [comment]
I've been using paint.net which supports tga pretty much perfectly, but thanks for replying.
