### ISSUE TITLE
Reverse implementation

### ISSUE THREAD

**Issue by Cypert** [xdanieldzd/GXTConvert#4]
Would it be possible to add the option to convert the opposite way (PNG->GXT)?

**Comment by xdanieldzd** [comment]
Probably possible, but it's not planned. My exporters/converters were, for the most part, always meant to be one-way conversions from a game's custom format, to a common standard like PNG (for datamining and documentation purposes), not the other way round.

Of course, everyone is free to fork this project, add support for converting _to_ GXT, and maybe make a pull request, so that I could possibly merge the feature to master if it works well.
