### ISSUE TITLE
 GXT

### ISSUE THREAD

**Issue by ch1ppyone** [xdanieldzd/GXTConvert#7]
Hi, I would like to ask a question.
Analyzing the format of the game, I came across a texture format GXT.
I decided to take advantage of your utility. But it does not work with all textures, with only a few. I do not know what it can be connected, but some of it converts so good, but some textures convert with errors like "out of range of array". Samples are included.
https://yadi.sk/d/XFmNn0nPwjEUW

**Comment by xdanieldzd** [comment]
This should now be fixed by commit 605525a0c8a3423de6c80153a472cb4eab389b35. I backported some changes [from Scarlet](https://github.com/xdanieldzd/Scarlet) - which could already convert the samples you posted correctly - related to image dimensions, so GXTConvert is now capable of converting them as well.

I'll make a new build of this program eventually, but I am not working on it much anymore as I'm focusing on the aforementioned Scarlet instead, so I'd recommend you to either try out that project (which can convert a lot more than just GXTs!), or build GXTConvert yourself.

![Screenshot](http://i.imgur.com/ecv5jKd.png)
