### ISSUE TITLE
PNG to GXT

### ISSUE THREAD

**Issue by Ryijun** [xdanieldzd/GXTConvert#9]
Will reverse transformation from png to gxt?

**Comment by xdanieldzd** [comment]
See issue #4 and [Scarlet issue #1](https://github.com/xdanieldzd/Scarlet/issues/1). In short: PNG to GXT is planned for Scarlet (not GXTConvert), but it's low priority and hasn't been started yet.

**Comment by Ryijun** [comment]
Thank you very much. Then a small question. In VitaSDK have psp2gxt program, but what is it and why - is little known. Yes, it can do GXT-file from the DDS, TGA formats, but pasting the file in the game (Spelunky), nothing good comes out. He tried to shove the font in the game, but obtained only ragged characters. Can something advise? Is there anywhere on the network manuals for GXT container? I understand that it is a container for storing textures. But it is necessary, I believe that in such a container texture stored correctly. Not only this I understand.

**Comment by xdanieldzd** [comment]
I haven't used the psp2gxt tool from the SDK, so I can't help you with that, sorry. As for manuals, etc., the only pieces of documentation about GXT (that I know of) are the following sites:

http://www.vitadevwiki.com/index.php?title=GXT
https://github.com/vitasdk/vita-headers/tree/master/include/psp2/ (gxm.h and gxt.h, in particular)

They're incomplete and I had to do additional research into the format myself while writing GXTConvert. It has been roughly a year since I started work on the program, tho, so it's possible there's now other, more complete documentation that I am not aware of.
